services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: picky
      MYSQL_USER: picky
      MYSQL_PASSWORD: 1234

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"