server:
  address: 0.0.0.0
  port: 8080
  shutdown: graceful


spring:
  application:
    name: picky-backend
  config:
    import:
      - classpath:properties/redis.yml
      - classpath:properties/jwt.yml
      - classpath:properties/jpa.yml
      - classpath:properties/naver.yml
      - classpath:properties/google.yml
      - classpath:properties/kakao.yml
      - classpath:properties/frontend.yml
      - classpath:properties/swagger.yml
      - classpath:properties/temp-token.yml
      - classpath:properties/s3.yml
      - classpath:properties/tmdb.yml
      - classpath:properties/mail.yml
  security:
    strategy: MODE_INHERITABLETHREADLOCAL


---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:properties/mysql-local.yml
      - classpath:properties/elasticsearch-local.yml



---
spring:
  config:
    activate:
      on-profile: aws
    import:
      - classpath:properties/mysql-prod.yml
      - classpath:properties/elasticsearch-prod.yml
