server:
  address: 0.0.0.0
  port: 8080
  shutdown: graceful


spring:
  application:
    name: picky-backend
  config:
    import:
      #security
      - classpath:properties/naver.yml
      - classpath:properties/google.yml
      - classpath:properties/kakao.yml
      - classpath:properties/temp-token.yml
      - classpath:properties/jwt.yml
      #external
      - classpath:properties/tmdb.yml
      - classpath:properties/mail.yml
      #etc
      - classpath:properties/frontend.yml
      - classpath:properties/swagger.yml
      #DB
      - classpath:properties/mysql.yml
      - classpath:properties/jpa.yml
      - classpath:properties/redis.yml
      - classpath:properties/elasticsearch.yml
      - classpath:properties/s3.yml


  security:
    strategy: MODE_INHERITABLETHREADLOCAL